language: rust
rust:
  - stable
  - beta
  - 1.36.0
script: |
  cargo build --verbose &&
  cargo test  --verbose --all
matrix: # additional tests
  include:
  - rust: 1.36.0
    env: CLIPPY=YESPLEASE
    before_script: rustup component add clippy-preview
    script: cargo clippy --all -- -D warnings
  - rust: 1.36.0
    env: RUSTFMT=YESPLEASE
    before_script: rustup component add rustfmt-preview
    script: cargo fmt --all -- --check
cache: cargo
