language: rust
rust:
  - nightly
script: |
  cargo build --verbose &&
  cargo test  --verbose --all
matrix: # additional tests
  include:
  - rust: nightly
    env: CLIPPY=YESPLEASE
    before_script: rustup component add clippy-preview
    script: cargo clippy --all -- -D warnings
  - rust: nightly
    env: RUSTFMT=YESPLEASE
    before_script: rustup component add rustfmt-preview
    script: cargo fmt --all -- --check
cache: cargo
