[package]
name = "podserve"
version = "0.1.1"
authors = ["Pascal Hartig <phartig@rdrei.net>"]
edition = "2018"

[dependencies]
rss = "1.8.0"
id3 = "0.3.0"
rocket = "0.4.1"
rocket_contrib = "0.4.1"
url = "1.7.2"
structopt = "0.2.17"
log = "0.4.6"
pretty_env_logger = "0.3.0"
chrono = "0.4.6"
