pub struct Config {
    title: String,
    description: String,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            title: "PodServe Feed".to_string(),
            description: "A podcast feed generated by PodServe (https://github.com/passy/podserve)"
                .to_string(),
        }
    }
}
